version: '3'

services:
  backend:
    build:
      context: ./backend/server/
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8089:8089"

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: service-db
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - '3000:3000'
